# xhost +local:root
services:
  menager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4006:6006
      - 4011:5011
    volumes:
      - ./project:/app
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
    volumes:
      - ./grafana:/var/lib/grafana/dashboards
      - ./project:/app
    
  nvidia:
    image: mindprince/nvidia_gpu_prometheus_exporter:0.1
    restart: unless-stopped
    runtime: nvidia
